### ISSUE TITLE
support other jira than skywatch

### ISSUE THREAD

**Issue by jjoshm** [medwig/watson-jira#3]
url should not be hardcoded
https://github.com/medwig/watson-jira/blob/802224521454ef0414c158d65525f61497c40ae1/watson_jira/src/jira.py#L7

**Comment by PrimaMateria** [comment]
The intention was to use ~/.netrc to set the server URL. Or to run watson-jira init command which will generate the config file for you.

**Comment by jjoshm** [comment]
> The intention was to use ~/.netrc to set the server URL. Or to run watson-jira init command which will generate the config file for you.
